apiVersion: apps/v1
kind: Deployment
metadata:
    name: playground
spec:
    replicas: 1
    revisionHistoryLimit: 3
    selector:
        matchLabels:
            app: playground
    template:
        metadata:
            labels:
                app: playground
        spec:
            containers:
                - image: hub.docker.com/r/wil42/playground
                  name: playground
                  ports:
                      - containerPort: 8888
