# frozen_string_literal: true

BOX = {
  image: 'bento/ubuntu-24.04',
  version: '202510.26.0',
  name: 'tblochetS',
  provider: {
    cpu: 4,
    mem: 4096
  }.freeze,
  network: {
    addr: '192.168.56.110'
  }.freeze
}.freeze

Vagrant.configure('2') do |config|
  config.vm.box = BOX[:image]
  config.vm.box_version = BOX[:version]

  config.vm.hostname = "#{BOX[:name]}.local"
  config.vm.network 'private_network', ip: BOX[:network][:addr]
  config.vm.provider 'virtualbox' do |v|
    v.customize ['modifyvm', :id, '--name', BOX[:name]]
    v.memory = BOX[:provider][:mem]
    v.cpus = BOX[:provider][:cpu]
    v.gui = false
  end

  config.vm.provision 'shell', name: 'install-k3s', inline: <<-SHELL
  curl -sfL https://get.k3s.io -o /home/vagrant/k3s-install.sh
  sh /home/vagrant/k3s-install.sh \
    --write-kubeconfig-mode 0644 \
    --flannel-iface=eth1
  SHELL


  config.vm.provision 'shell', name: 'install-docker', inline: <<-SHELL
  apt-get update

  # Install required packages
  apt-get install -y ca-certificates curl gnupg git

  # Add Docker's official GPG key
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg

  # Add Docker repository
  echo \
    "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
    tee /etc/apt/sources.list.d/docker.list > /dev/null

  # Install Docker packages
  apt-get update
  apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

  # Add vagrant user to docker group
  usermod -aG docker vagrant
  SHELL

  config.vm.provision 'shell', name: 'create-sample-image', inline: <<-SHELL
  docker buildx build \
    -t "localhost:5000/iot-sample:1.0" \
    --platform linux/amd64 /vagrant/image

  docker run -d \
    -p 5000:5000 \
    --restart=always \
    --name registry registry:2

  docker push localhost:5000/iot-sample:1.0
  SHELL

  # The last option is a catch-all rule, since a default backend
  # is not working on this version of traefik
  # See: https://github.com/traefik/traefik/blob/4a87f05acfa2beb0211cee6e2ad4d002289752b5/pkg/provider/kubernetes/ingress/kubernetes.go#L286
  config.vm.provision 'shell', name: 'setup-ingress', inline: <<-SHELL
  k3s kubectl create ingress ingress \
    --rule='app1.com/=app-one:80' \
    --rule='app2.com/=app-two:80'\
    --rule='app3.com/=app-three:80' \
    --rule='/=app-three:80' \
    -o yaml
  SHELL

  config.vm.provision 'shell', name: 'setup-app-one', inline: <<-SHELL
  k3s kubectl create service clusterip app-one \
    --tcp=80:8080 \
    -o yaml
  k3s kubectl create deployment app-one \
    --image=localhost:5000/iot-sample:1.0 \
    --port=8080 \
    -o yaml
  k3s kubectl set env deployment/app-one \
    MESSAGE="hello from app1"
  SHELL


  config.vm.provision 'shell', name: 'setup-app-two', inline: <<-SHELL
  k3s kubectl create service clusterip app-two \
    --tcp=80:8080 \
    -o yaml
  k3s kubectl create deployment app-two \
    --image=localhost:5000/iot-sample:1.0 \
    --port=8080 \
    --replicas=3 \
    -o yaml
  k3s kubectl set env deployment/app-two \
    MESSAGE="hello from app2"
  SHELL

  config.vm.provision 'shell', name: 'setup-app-three', inline: <<-SHELL
  k3s kubectl create service clusterip app-three \
    --tcp=80:8080 \
    -o yaml
  k3s kubectl create deployment app-three \
    --image=localhost:5000/iot-sample:1.0 \
    --port=8080 \
    -o yaml
  k3s kubectl set env deployment/app-three \
    MESSAGE="hello from app3"
  SHELL
end
