# frozen_string_literal: true

secrets = {
  'agent_token_file' => '/vagrant/secret'
}

SERVICES = {
  'server' => {
    ip: '192.168.56.110',
    hostname: 'tblochetS'
  },
  'worker' => {
    ip: '192.168.56.111',
    hostname: 'tblochetSW'
  }
}

def configure_machine(box, name, provider_config)
  box.vm.hostname = "#{SERVICES[name][:hostname]}.local"
  box.vm.network 'private_network', ip: SERVICES[name][:ip]
  box.vm.provider 'virtualbox' do |v|
    v.customize ['modifyvm', :id, '--name', SERVICES[name][:hostname]]
    v.memory = provider_config['mem']
    v.cpus = provider_config['cpu']
    v.gui = false
  end
end

Vagrant.configure('2') do |config|
  # https://docs.vagrantup.com.

  config.vm.box = 'bento/ubuntu-24.04'
  config.vm.box_version = '202510.26.0'

  config.vm.provision 'shell', name: 'get-k3s-installer', inline: <<-SHELL
  curl -sfL https://get.k3s.io -o /home/vagrant/k3s-install.sh
  SHELL

  # Define configuration for Controller
  config.vm.define SERVICES['server'][:hostname] do |server|
    configure_machine(server, 'server', { 'mem' => 2048, 'cpu' => 2 })
    server.vm.provision 'shell', env: {
      'K3S_AGENT_TOKEN_FILE' => secrets['agent_token_file']
    }, inline: 'sh /home/vagrant/k3s-install.sh'
  end

  # Define configuration for Service Worker
  config.vm.define SERVICES['worker'][:hostname] do |worker|
    configure_machine(worker, 'worker', { 'mem' => 512, 'cpu' => 1 })
    worker.vm.provision 'shell', env: {
      'K3S_TOKEN_FILE' => secrets['agent_token_file'],
      'K3S_URL' => "https://#{SERVICES['server'][:ip]}:6443"
    }, inline: 'echo $K3S_TOKEN_FILE; sh /home/vagrant/k3s-install.sh'
  end
end
