#!/usr/bin/env bash
set -euo pipefail

BASE_IMAGE_URL="https://download.fedoraproject.org/pub/fedora/linux/releases/44/Cloud/x86_64/images/Fedora-Cloud-Base-Generic-44-1.7.x86_64.qcow2"
BASE_IMAGE_FILE=`basename ${BASE_IMAGE_URL}`

if [ ! -f "$BASE_IMAGE_FILE" ]
then
  curl -sfLO "$BASE_IMAGE_URL"
fi

VM_NAME="$2"
DISK="${VM_NAME}.qcow2"

create() {
  qemu-img create -f qcow2 -F qcow2 -b "$BASE_IMAGE_FILE" "$DISK"
  cat > "${VM_NAME}-user-data.yaml" <<EOF
#cloud-config
hostname: ${VM_NAME}
users:
  - name: fedora
    ssh_authorized_keys:
      - $(cat "$HOME/.ssh/id_ed25519.pub")
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: wheel

package_update: true
package_upgrade: true

packages:
  - git
  - make
  - podman-compose
  - podman-docker
  - podman-machine
  - curl
  - coreutils

bootcmd:
  - mkdir -p /opt/iot/installers
runcmd:
  - /opt/iot/installers/k3d
  - /opt/iot/installers/kubectl
  - /opt/iot/installers/argocd
  - /opt/iot/installers/helm
EOF
  cat >> "${VM_NAME}-user-data.yaml" <<'EOF'
write_files:
  - path: /opt/iot/installers/k3d
    content: |
      #!/usr/bin/env bash
      set -euo pipefail
      if [ -f /var/run/docker.sock ]
      then
        ln -sv /run/podman/podman.sock /var/run/docker.sock
      fi
      if ! command -v k3d
      then
        curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
        if ! systemctl is-active podman.socket
        then
          systemctl enable --now podman.socket
          mkdir -pv /etc/containers/containers.conf.d
          echo 'service_timeout=0' > /etc/containers/containers.conf.d/timeout.conf
          printf '[containers]\nlog_driver = "k8s-file"' >> /etc/containers/containers.conf
        fi
      fi
    owner: root:root
    permissions: "0500"

  - path: /opt/iot/installers/kubectl
    content: |
      #!/usr/bin/env bash
      set -euo pipefail
      if ! command -v kubectl
      then
        temp_dir=`mktemp -d`
        curl -sfL "https://dl.k8s.io/release/v1.37.1/bin/linux/amd64/kubectl" \
          -o "$temp_dir/kubectl"
        curl -sfL "https://dl.k8s.io/release/v1.37.1/bin/linux/amd64/kubectl.sha256" \
          -o "$temp_dir/kubectl.sha256"
          printf " kubectl" >> "$temp_dir/kubectl.sha256"
          pushd "$temp_dir"
          sha256sum --check kubectl.sha256
          install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        popd
        rm -rf "$temp_dir"
      fi
    owner: root:root
    permissions: "0500"
  - path: /opt/iot/installers/argocd
    content: |
      #!/usr/bin/env bash
      set -euo pipefail
      if ! `command -v argocd`
      then
        curl -sSL \
          -o /tmp/argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/download/v3.5.3/argocd-linux-amd64
        sudo install -m 555 /tmp/argocd-linux-amd64 /usr/local/bin/argocd
        rm /tmp/argocd-linux-amd64
      fi
    owner: root:root
    permissions: "0500"

  - path: /opt/iot/installers/helm
    content: |
      #!/usr/bin/env bash

      HELM_VERSION="v4.3.0"
      HELM_TARBALL="helm-$HELM_VERSION-linux-amd64.tar.gz"
      HELM_TARBALL_URL="https://get.helm.sh/$HELM_TARBALL"
      HELM_TARBALL_SUM_URL="https://get.helm.sh/$HELM_TARBALL.sha256sum"

      HELM_TEMP_DIR=`mktemp --directory`
      pushd "$HELM_TEMP_DIR"
      curl -sfLO "$HELM_TARBALL_URL"
      curl -sfLO "$HELM_TARBALL_SUM_URL"
      sha256sum -c "$HELM_TARBALL.sha256sum" 2>&1 >/dev/null|| (rm -f "$HELM_TARBALL_SUM_URL" "$HELM_TARBALL_URL"; exit 1)
      tar xf "$HELM_TARBALL"
      install -v linux-amd64/helm /usr/local/bin/helm
      popd
      rm -rf "$HELM_TEMP_DIR"
    owner: root:root
    permissions: "0500"
EOF

cat > "${VM_NAME}-meta-data.yaml" <<EOF
instance-id: ${VM_NAME}
local-hostname: ${VM_NAME}
EOF
}

install() {
  virt-install \
    --connect qemu:///system \
    --name "$VM_NAME" \
    --memory 8192 \
    --vcpus 8 \
    --disk path="$DISK",format=qcow2 \
    --import \
    --os-variant fedora-unknown \
    --network network=default\
    --graphics none \
    --console pty,target_type=serial \
    --cloud-init user-data="${VM_NAME}-user-data.yaml",meta-data="${VM_NAME}-user-data.yaml" \
    --noautoconsole
}

case "$1" in
  "create")
    create
    ;;
  "install")
    install
    ;;
  *)
    printf 'Usage: setup-vm <create | install> <name>\n'
    ;;
esac
